# Site settings
title: Wenhu Chen's Home Page
email: wenhuchen@uwaterloo.ca
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wenhuchen.github.io" # the base hostname & protocol for your site
github: wenhuchen
googlescholar: https://scholar.google.com/citations?user=U8ShbhUAAAAJ&hl=en
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
encoding: "utf-8"
# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
